# Generated by Django 4.1 on 2022-11-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_park'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='leaves',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='park',
            name='length',
        ),
        migrations.AddField(
            model_name='park',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
